[workspace]
resolver = "3"
members = [
    "clr_profiler",
    "clr_profiler_macros",
    "test_profilers",
    "profile", 
    "ssl_pin_bypass", 
    "load_test", 
    "log_init", 
    "air_327_fix",
]

[workspace.dependencies]
log = "0.4"
uuid = "0.8"
