[package]
name = "profile"
version = "0.1.0"
description = "Launch target with profiler"
edition = "2021"

[dependencies]
bitflags = "2.9.1"
uuid ={ workspace = true }
clap = { version = "4.5.43", features = ["derive"] }
