[package]
name = "profile"
version = "0.1.0"
description = "Launch target with profiler"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
uuid ={ workspace = true }
clap = { version = "4.5.43", features = ["derive"] }
